### PR TITLE
ExcludeMouseTracking as marker component to opt-out a camera from mouse tracking

### LINKED ISSUE #18: Incompatible with kayak_ui (and other cameras with custom projections)
This crate does not work with the kayak_ui crate due to its use of a custom projection.

Even with a MainCamera given to a standard bevy camera and no user-defined interaction between this crate and the kayak_ui camera, it is still considered when querying for cameras and thus this plugin panics with 'only orthographic cameras are supported' when ideally it shouldn't be forced to.

I am not saying this crate needs to support custom cameras, but having the option to manually opt-out for a custom camera so that the app can use both plugins separately is something I believe should be added.

I will open a PR to fix this issue.

### PR DESCRIPTION
**Pull request by EmmettJayhart**
This PR resolves #18 about incompatible cameras, and possibly other issues that may have come down the line by allowing the user to manually opt-out individual cameras.

ExcludeMouseTracking is a marker component for any camera the user wishes to opt-out of mouse tracking.

By having this marker, a camera will not be given a MousePos or a MousePosWorld, and will also be excluded from the query when update_pos_ortho runs.

If an entity that has a MainCamera component also has an ExcludeTracking component, it will panic with an appropriate error message.

This PR does not allow users to use custom projections and mouse tracking on the same camera, it only allows the app to both have cameras for mouse tracking, and separate cameras with custom projections.

### CODE REVIEW

File: src/mouse_pos.rs [hunk 1]
```diff
@@ -81,9 +86,12 @@ impl Display for MousePos {
     }
 }
 
+type NeedScreenspaceTracking = (Without<MousePos>, Without<ExcludeMouseTracking>);
+type NeedWorldspaceTracking = (Without<MousePosWorld>, Without<ExcludeMouseTracking>);
```
Comment (joseph-gio) [inline src/mouse_pos.rs]: These type aliases are nice, I always like self-documenting code

File: src/lib.rs [hunk 2]
```diff
@@ -164,6 +171,42 @@
...
+//! ```
+//!
+//! If you add the `ExcludeMouseTracking` component to an entity that also has the `MainCamera` component, you will find that the app panics:
+//!
+//! ```text
+//! thread 'main' panicked at 'excluded main camera -- consider removing the ExcludeTracking component from the main camera', src\mouse_pos.rs:216:9
+//! ```
+//!
+//! You should remove either `ExcludeMouseTracking` or `MainCamera`, as they should not be used together.
+//!
```
Comment (joseph-gio) [inline src/lib.rs]: Good note, but this should be in the docs for `ExcludeMouseTracking`, not the README.

File: src/mouse_pos.rs [hunk 3]
```diff
@@ -140,12 +148,12 @@ impl Deref for MousePosWorld {
...
 fn update_pos_ortho(
     mut tracking: Query<(Entity, &mut MousePosWorld, &MousePos), Changed<MousePos>>,
-    cameras: Query<(&GlobalTransform, &OrthographicProjection)>,
+    cameras: Query<(&GlobalTransform, &OrthographicProjection), Without<ExcludeMouseTracking>>,
 ) {
     for (camera, mut world, screen) in tracking.iter_mut() {
         let (camera, proj) = cameras
             .get(camera)
-            .expect("only orthographic cameras are supported");
+            .expect("only orthographic cameras are supported -- consider adding an ExcludeTracking component");
```
Comment (joseph-gio) [inline src/mouse_pos.rs]:
```suggestion
            .expect("only orthographic cameras are supported -- consider adding an ExcludeMouseTracking component");
```

File: src/mouse_pos.rs [hunk 4]
```diff
@@ -201,6 +210,10 @@ fn find_main_camera(
             }
             Some(main)
         }
+    };
+    // panic if the query finds an entity with both MainCamera and ExcludeTracking components
+    if !excluded_main.is_empty() {
+        panic!("excluded main camera -- consider removing the ExcludeTracking component from the main camera")
```
Comment (joseph-gio) [inline src/mouse_pos.rs]:
```suggestion
        panic!("excluded main camera -- consider removing the ExcludeMouseTracking component from the main camera")
```

File: src/mouse_pos.rs [hunk 5]
```diff
@@ -62,6 +62,11 @@ impl Plugin for MousePosPlugin {
     }
 }
 
+/// Marker component for cameras to be excluded from tracking.
+/// Any camera with this component will not be given a [`MousePos`] or [`MousePosWorld`] component.
```
Comment (joseph-gio) [inline src/mouse_pos.rs]:
```suggestion
/// Marker component for cameras that should be excluded from mouse tracking.
/// Any entity with this component will be ignored by [`MousePosPlugin`].
```

**Review by joseph-gio — CHANGES_REQUESTED** [review]
Thank you for bringing this issue to my attention. Ideally I would like to provide some way of supporting custom projections, but this is a good short-term solution.

Once you resolve the issues, I'll merge and publish it ASAP.

File: src/mouse_pos.rs (hunk 1 above)
Comment (EmmettJayhart) [reply src/mouse_pos.rs]: Thanks, it arised from the need to please clippy, as well as trying to avoid some ugly rustfmt formatting.

**Comment by EmmettJayhart** [comment]
I have applied the suggested changes as well as updated some of the documentation.

It looks like the failed test suite is due to cargo running tests on the documentation code.
If you're looking for a fix for this, it's just the doctest field in Cargo.toml under [lib]

**Comment by joseph-gio** [comment]
Keeping the doctests up to date is very important, but I can fix up the last issues if you don't want to go back and forth with CI.

**Comment by EmmettJayhart** [comment]
Looking at how you've done the other tests, I see where it's going wrong.

**Comment by EmmettJayhart** [comment]
I've fixed up the doctests. This was my first time ever using them so it was a great learning experience!

**Review by joseph-gio — APPROVED** [review]
Looks good. Thanks for contributing!
